---
title: "Chipseq"
author: "riya"
---


```{r}
#loading libraries----
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DiffBind")
library(DiffBind)
library(tidyverse)
library(rtracklayer)
library(ggplot2)
```


```{r}
#loading data----
setwd("/path/to/my/data")
samples <- read.csv("/path/to/my/data.csv")
names(samples)

metadata <- dba(sampleSheet="/path/to/my/metadata.csv")
metadata
plot(metadata)
head(metadata$peaks[[1]])

```

```{r}
#plotting Occupany Analysis----
dba.plotHeatmap(metadata, margin = 15)
```

```{r}
#counting reads----
metadata.counted <- dba.count(metadata)
metadata.counted
info <- dba.show(metadata.counted)
libsizes <- cbind(LibReads=info$Reads, FRiP=info$FRiP,
                  PeakReads=round(info$Reads * info$FRiP))
rownames(libsizes) <- info$ID
libsizes

```
```{r}
#normalization----
metadata.counted.norm<- dba.normalize(metadata.counted)
norm <- dba.normalize(metadata.counted.norm, bRetrieve=TRUE)
norm

normlibs <- cbind(FullLibSize=norm$lib.sizes, NormFacs=norm$norm.factors,
                  NormLibSize=round(norm$lib.sizes/norm$norm.factors))
rownames(normlibs) <- info$ID
normlibs
```

```{r}
#contrast AND differential Analysis----
#DESeq2 defualt analysis
metadata.counted.cont <- dba.contrast(metadata.counted.norm,
                                 categories = DBA_CONDITION)

samples_summary <- dba.show(metadata.counted.cont)
print(samples_summary)

metadata.counted.analyzed<- dba.analyze(metadata.counted.cont)
dba.show(metadata.counted.analyzed, bContrast= TRUE)
```

```{r}
#plotting counted PCA----
dba.plotHeatmap(metadata.counted, margin =20)
dba.plotPCA(metadata.counted,  attributes= DBA_TISSUE, label=DBA_FACTOR, dotSize= 0.75, labelSize=0.75)
dba.plotPCA(metadata.counted,  attributes= DBA_FACTOR, label=DBA_TISSUE, dotSize= 0.75, labelSize=0.75)


samples[,DBA_TISSUE]
samples[,DBA_FACTOR]
samples[,DBA_CONDITION]
samples[,DBA_GROUP]
samples[,DBA_ID]



samples <- dba.show(metadata.counted)

unique_factors <- unique(samples$Factor)


for (factor in unique_factors) {
  factor_indices <- which(samples$Factor == factor)
  subset_data <- dba(metadata.counted, mask = factor_indices)
  dba.plotPCA(subset_data, attributes=DBA_TISSUE, label=DBA_CONDITION, dotSize=0.75, labelSize=0.75)
}



samples <- dba.show(metadata.counted)
unique_factors <- unique(samples$Factor)

# Looping through each unique tissue type and create a PCA plot
for (factor in unique_factors) {
  factor_indices <- which(samples$Factor == factor)
  pdf_filename <- paste0("PCA_plot_", factor, ".pdf")
  pdf(pdf_filename)
  subset_data <- dba(metadata.counted, mask = factor_indices)
  dba.plotPCA(subset_data, attributes=DBA_TISSUE, label=DBA_CONDITION, dotSize=0.75, labelSize=0.75)
  dev.off()
}
```
